### ISSUE TITLE
Installed via plugin process but not showing as a new app in Kibana

### ISSUE THREAD

**Issue by bigtoerag** [packetbeat/bonito#1]
I have successfully installed the package from GIT via the ./pugin method and the files are all deployed alongside timelion but the app never shows up in the Kibana app panel.

```
root@xxxxx:~# /opt/kibana/bin/kibana plugin -i tsg/bonito
Installing bonito
Attempting to extract from https://download.elastic.co/tsg/bonito/bonito-latest.tar.gz
Attempting to extract from https://github.com/tsg/bonito/archive/master.tar.gz
Downloading unknown number of bytes
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
```

**Comment by tsg** [comment]
This project is not a Kibana plugin at the moment. I like the idea of transforming it into one, and hope to find the time to do it, but this isn't a finished project at the moment.

**Comment by bigtoerag** [comment]
Is there a way I can access the GUI from its current install outlined above?
